name: "Terraform-Apply-Infra-Release"

on:
  push:
    branches:
      - main
      
jobs:
  terraform:
    name: "Terraform"      
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      
    env:
      #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
      #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ID }}
      AWS_REGION: "eu-south-2"
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Debug OIDC claims
        run: |
          curl -sSL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | \
            jq -R 'split(".") | .[1] | @base64d | fromjson'        
              
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                aws-region: ${{ env.AWS_REGION }}   
                audience: sts.amazonaws.com
        
      - name: Check or Create S3 Backend Bucket
        run: |
          BUCKET_NAME="santsa-terraform-actions"
          if aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
            echo "The buket exists."
          else
            echo "The bucket does not exists. Creating it a eu-south-2..."
            aws s3api create-bucket \
              --bucket "$BUCKET_NAME" \
              --region eu-south-2 \
              --create-bucket-configuration LocationConstraint=eu-south-2
          fi
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Terraform Init
        id: init
        run: terraform init
        
      - name: Terraform Plan
        id: plan
        if: github.event_name == 'push'
        run: terraform plan -no-color
        continue-on-error: true
        
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
        
      #- name: Terraform Apply
      # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      # run: terraform apply -auto-aprove
      
